# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sitac_ui.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 480)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        MainWindow.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(12)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pages = QtWidgets.QStackedWidget(self.centralwidget)
        self.pages.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pages.sizePolicy().hasHeightForWidth())
        self.pages.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.pages.setPalette(palette)
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.pages.setFont(font)
        self.pages.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pages.setObjectName("pages")
        self.ClockPage = QtWidgets.QWidget()
        self.ClockPage.setObjectName("ClockPage")
        self.statusLabel = QtWidgets.QLabel(self.ClockPage)
        self.statusLabel.setGeometry(QtCore.QRect(9, 378, 121, 75))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.statusLabel.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.statusLabel.setFont(font)
        self.statusLabel.setObjectName("statusLabel")
        self.timeLabel = QtWidgets.QLabel(self.ClockPage)
        self.timeLabel.setGeometry(QtCore.QRect(240, 50, 271, 91))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.timeLabel.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(48)
        self.timeLabel.setFont(font)
        self.timeLabel.setObjectName("timeLabel")
        self.settingsButton = QtWidgets.QPushButton(self.ClockPage)
        self.settingsButton.setGeometry(QtCore.QRect(640, 400, 141, 61))
        self.settingsButton.setObjectName("settingsButton")
        self.nextAlarmLabel = QtWidgets.QLabel(self.ClockPage)
        self.nextAlarmLabel.setGeometry(QtCore.QRect(270, 150, 201, 20))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.nextAlarmLabel.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.nextAlarmLabel.setFont(font)
        self.nextAlarmLabel.setObjectName("nextAlarmLabel")
        self.pages.addWidget(self.ClockPage)
        self.SettingsPage = QtWidgets.QWidget()
        self.SettingsPage.setObjectName("SettingsPage")
        self.settingsTitleLabel = QtWidgets.QLabel(self.SettingsPage)
        self.settingsTitleLabel.setGeometry(QtCore.QRect(240, 50, 281, 71))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(15, 255, 111))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(15, 255, 111))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.settingsTitleLabel.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(32)
        self.settingsTitleLabel.setFont(font)
        self.settingsTitleLabel.setObjectName("settingsTitleLabel")
        self.homeButton = QtWidgets.QPushButton(self.SettingsPage)
        self.homeButton.setGeometry(QtCore.QRect(640, 400, 141, 61))
        self.homeButton.setObjectName("homeButton")
        self.setAlarmButton = QtWidgets.QPushButton(self.SettingsPage)
        self.setAlarmButton.setGeometry(QtCore.QRect(30, 400, 141, 61))
        self.setAlarmButton.setObjectName("setAlarmButton")
        self.brewButton = QtWidgets.QPushButton(self.SettingsPage)
        self.brewButton.setGeometry(QtCore.QRect(30, 330, 141, 61))
        self.brewButton.setObjectName("brewButton")
        self.lightsButton = QtWidgets.QPushButton(self.SettingsPage)
        self.lightsButton.setGeometry(QtCore.QRect(190, 330, 151, 61))
        self.lightsButton.setObjectName("lightsButton")
        self.alarmTimeInput = QtWidgets.QTimeEdit(self.SettingsPage)
        self.alarmTimeInput.setGeometry(QtCore.QRect(30, 240, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.alarmTimeInput.setFont(font)
        self.alarmTimeInput.setTime(QtCore.QTime(12, 0, 0))
        self.alarmTimeInput.setObjectName("alarmTimeInput")
        self.volumeSlider = QtWidgets.QSlider(self.SettingsPage)
        self.volumeSlider.setGeometry(QtCore.QRect(470, 230, 241, 22))
        self.volumeSlider.setMaximum(50)
        self.volumeSlider.setSliderPosition(25)
        self.volumeSlider.setOrientation(QtCore.Qt.Horizontal)
        self.volumeSlider.setObjectName("volumeSlider")
        self.volumeLabel = QtWidgets.QLabel(self.SettingsPage)
        self.volumeLabel.setGeometry(QtCore.QRect(550, 200, 91, 20))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.volumeLabel.setPalette(palette)
        self.volumeLabel.setObjectName("volumeLabel")
        self.toneLabel = QtWidgets.QLabel(self.SettingsPage)
        self.toneLabel.setGeometry(QtCore.QRect(520, 270, 151, 20))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.toneLabel.setPalette(palette)
        self.toneLabel.setObjectName("toneLabel")
        self.tonesList = QtWidgets.QComboBox(self.SettingsPage)
        self.tonesList.setGeometry(QtCore.QRect(520, 300, 141, 22))
        self.tonesList.setObjectName("tonesList")
        self.delayTimeInput = QtWidgets.QTimeEdit(self.SettingsPage)
        self.delayTimeInput.setGeometry(QtCore.QRect(200, 240, 141, 41))
        self.delayTimeInput.setObjectName("delayTimeInput")
        self.alarmTimeLabel = QtWidgets.QLabel(self.SettingsPage)
        self.alarmTimeLabel.setGeometry(QtCore.QRect(60, 210, 81, 20))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.alarmTimeLabel.setPalette(palette)
        self.alarmTimeLabel.setObjectName("alarmTimeLabel")
        self.label = QtWidgets.QLabel(self.SettingsPage)
        self.label.setGeometry(QtCore.QRect(220, 210, 81, 20))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label.setPalette(palette)
        self.label.setObjectName("label")
        self.alarmOffButton = QtWidgets.QPushButton(self.SettingsPage)
        self.alarmOffButton.setGeometry(QtCore.QRect(190, 400, 151, 61))
        self.alarmOffButton.setObjectName("alarmOffButton")
        self.pages.addWidget(self.SettingsPage)
        self.AlarmPage = QtWidgets.QWidget()
        self.AlarmPage.setObjectName("AlarmPage")
        self.wakeUpLabel = QtWidgets.QLabel(self.AlarmPage)
        self.wakeUpLabel.setGeometry(QtCore.QRect(60, 70, 611, 161))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.wakeUpLabel.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(36)
        self.wakeUpLabel.setFont(font)
        self.wakeUpLabel.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.wakeUpLabel.setScaledContents(False)
        self.wakeUpLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.wakeUpLabel.setObjectName("wakeUpLabel")
        self.outButton = QtWidgets.QPushButton(self.AlarmPage)
        self.outButton.setGeometry(QtCore.QRect(190, 250, 151, 61))
        self.outButton.setObjectName("outButton")
        self.snoozeButton = QtWidgets.QPushButton(self.AlarmPage)
        self.snoozeButton.setGeometry(QtCore.QRect(400, 250, 161, 61))
        self.snoozeButton.setObjectName("snoozeButton")
        self.pages.addWidget(self.AlarmPage)
        self.SnoozePage = QtWidgets.QWidget()
        self.SnoozePage.setObjectName("SnoozePage")
        self.snoozeLabel = QtWidgets.QLabel(self.SnoozePage)
        self.snoozeLabel.setGeometry(QtCore.QRect(120, 110, 511, 61))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.snoozeLabel.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(36)
        self.snoozeLabel.setFont(font)
        self.snoozeLabel.setObjectName("snoozeLabel")
        self.snoozeOffButton = QtWidgets.QPushButton(self.SnoozePage)
        self.snoozeOffButton.setGeometry(QtCore.QRect(280, 200, 191, 41))
        self.snoozeOffButton.setObjectName("snoozeOffButton")
        self.pages.addWidget(self.SnoozePage)
        self.verticalLayout.addWidget(self.pages)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.pages.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.statusLabel.setText(_translate("MainWindow", "Alarm: OFF\n"
"Brew:  OFF\n"
"Alarm: OFF"))
        self.timeLabel.setText(_translate("MainWindow", "07:00 AM"))
        self.settingsButton.setText(_translate("MainWindow", "Settings"))
        self.nextAlarmLabel.setText(_translate("MainWindow", "Next alarm: 7:00 AM"))
        self.settingsTitleLabel.setText(_translate("MainWindow", "Alarm Settings"))
        self.homeButton.setText(_translate("MainWindow", "Home"))
        self.setAlarmButton.setText(_translate("MainWindow", "Set Alarm"))
        self.brewButton.setText(_translate("MainWindow", "Brew: OFF"))
        self.lightsButton.setText(_translate("MainWindow", "Lights: OFF"))
        self.volumeLabel.setText(_translate("MainWindow", "Volume: 25"))
        self.toneLabel.setText(_translate("MainWindow", "Alarm tone: Buzzer"))
        self.alarmTimeLabel.setText(_translate("MainWindow", "Alarm time"))
        self.label.setText(_translate("MainWindow", "Delay time"))
        self.alarmOffButton.setText(_translate("MainWindow", "Alarm Off"))
        self.wakeUpLabel.setText(_translate("MainWindow", "Rise and Shine\n"
"The current time is 7:00 AM"))
        self.outButton.setText(_translate("MainWindow", "Dimiss"))
        self.snoozeButton.setText(_translate("MainWindow", "Snooze"))
        self.snoozeLabel.setText(_translate("MainWindow", "Snoozing until 7:05 AM"))
        self.snoozeOffButton.setText(_translate("MainWindow", "Snooze off"))

