# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sitac_ui_gold_theme.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 480)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        MainWindow.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(12)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pages = QtWidgets.QStackedWidget(self.centralwidget)
        self.pages.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pages.sizePolicy().hasHeightForWidth())
        self.pages.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.pages.setPalette(palette)
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.pages.setFont(font)
        self.pages.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pages.setAutoFillBackground(True)
        self.pages.setObjectName("pages")
        self.ClockPage = QtWidgets.QWidget()
        self.ClockPage.setObjectName("ClockPage")
        self.gridLayout = QtWidgets.QGridLayout(self.ClockPage)
        self.gridLayout.setObjectName("gridLayout")
        self.nextAlarmLabel = QtWidgets.QLabel(self.ClockPage)
        self.nextAlarmLabel.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nextAlarmLabel.sizePolicy().hasHeightForWidth())
        self.nextAlarmLabel.setSizePolicy(sizePolicy)
        self.nextAlarmLabel.setMaximumSize(QtCore.QSize(500, 16777215))
        self.nextAlarmLabel.setBaseSize(QtCore.QSize(0, 0))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(179, 163, 105))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(179, 163, 105))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.nextAlarmLabel.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.nextAlarmLabel.setFont(font)
        self.nextAlarmLabel.setToolTipDuration(-1)
        self.nextAlarmLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.nextAlarmLabel.setLineWidth(1)
        self.nextAlarmLabel.setMidLineWidth(0)
        self.nextAlarmLabel.setScaledContents(False)
        self.nextAlarmLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.nextAlarmLabel.setIndent(-1)
        self.nextAlarmLabel.setObjectName("nextAlarmLabel")
        self.gridLayout.addWidget(self.nextAlarmLabel, 6, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.timeLabel = QtWidgets.QLabel(self.ClockPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.timeLabel.sizePolicy().hasHeightForWidth())
        self.timeLabel.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(179, 163, 105))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(179, 163, 105))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.timeLabel.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(48)
        self.timeLabel.setFont(font)
        self.timeLabel.setTextFormat(QtCore.Qt.PlainText)
        self.timeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.timeLabel.setObjectName("timeLabel")
        self.gridLayout.addWidget(self.timeLabel, 0, 1, 1, 1, QtCore.Qt.AlignHCenter)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 10, 1, 1, 1)
        self.settingsButton = QtWidgets.QPushButton(self.ClockPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.settingsButton.sizePolicy().hasHeightForWidth())
        self.settingsButton.setSizePolicy(sizePolicy)
        self.settingsButton.setMinimumSize(QtCore.QSize(120, 40))
        self.settingsButton.setMaximumSize(QtCore.QSize(120, 40))
        self.settingsButton.setAutoFillBackground(True)
        self.settingsButton.setObjectName("settingsButton")
        self.gridLayout.addWidget(self.settingsButton, 10, 2, 1, 2, QtCore.Qt.AlignRight|QtCore.Qt.AlignBottom)
        spacerItem1 = QtWidgets.QSpacerItem(20, 150, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.gridLayout.addItem(spacerItem1, 9, 1, 1, 1)
        self.statusLabel = QtWidgets.QLabel(self.ClockPage)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(179, 163, 105))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(179, 163, 105))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.statusLabel.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.statusLabel.setFont(font)
        self.statusLabel.setObjectName("statusLabel")
        self.gridLayout.addWidget(self.statusLabel, 10, 0, 1, 1, QtCore.Qt.AlignLeft|QtCore.Qt.AlignBottom)
        self.pages.addWidget(self.ClockPage)
        self.SettingsPage = QtWidgets.QWidget()
        self.SettingsPage.setObjectName("SettingsPage")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.SettingsPage)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.settingsTitleLabel = QtWidgets.QLabel(self.SettingsPage)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(179, 163, 105))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(15, 255, 111))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(179, 163, 105))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(15, 255, 111))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.settingsTitleLabel.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(36)
        self.settingsTitleLabel.setFont(font)
        self.settingsTitleLabel.setObjectName("settingsTitleLabel")
        self.gridLayout_5.addWidget(self.settingsTitleLabel, 0, 2, 1, 5, QtCore.Qt.AlignHCenter)
        self.alarmTimeLabel = QtWidgets.QLabel(self.SettingsPage)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(179, 163, 105))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(179, 163, 105))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.alarmTimeLabel.setPalette(palette)
        self.alarmTimeLabel.setObjectName("alarmTimeLabel")
        self.gridLayout_5.addWidget(self.alarmTimeLabel, 1, 0, 1, 2, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignBottom)
        self.label = QtWidgets.QLab-el(self.SettingsPage)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(179, 163, 105))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(179, 163, 105))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label.setPalette(palette)
        self.label.setObjectName("label")
        self.gridLayout_5.addWidget(self.label, 1, 2, 1, 2, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignBottom)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem2, 3, 5, 1, 1)
        self.volumeSlider = QtWidgets.QSlider(self.SettingsPage)
        self.volumeSlider.setMinimumSize(QtCore.QSize(200, 0))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Link, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Link, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 153, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Link, brush)
        self.volumeSlider.setPalette(palette)
        self.volumeSlider.setMaximum(50)
        self.volumeSlider.setSliderPosition(25)
        self.volumeSlider.setOrientation(QtCore.Qt.Horizontal)
        self.volumeSlider.setObjectName("volumeSlider")
        self.gridLayout_5.addWidget(self.volumeSlider, 3, 7, 1, 1)
        self.homeButton = QtWidgets.QPushButton(self.SettingsPage)
        self.homeButton.setMinimumSize(QtCore.QSize(120, 40))
        self.homeButton.setObjectName("homeButton")
        self.gridLayout_5.addWidget(self.homeButton, 8, 7, 1, 1, QtCore.Qt.AlignRight)
        self.lightsButton = QtWidgets.QPushButton(self.SettingsPage)
        self.lightsButton.setMinimumSize(QtCore.QSize(135, 40))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.lightsButton.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lightsButton.setFont(font)
        self.lightsButton.setStyleSheet("")
        self.lightsButton.setObjectName("lightsButton")
        self.gridLayout_5.addWidget(self.lightsButton, 6, 3, 1, 1, QtCore.Qt.AlignHCenter)
        self.tonesList = QtWidgets.QComboBox(self.SettingsPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tonesList.sizePolicy().hasHeightForWidth())
        self.tonesList.setSizePolicy(sizePolicy)
        self.tonesList.setObjectName("tonesList")
        self.gridLayout_5.addWidget(self.tonesList, 6, 7, 1, 1)
        self.alarmTimeInput = QtWidgets.QTimeEdit(self.SettingsPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.alarmTimeInput.sizePolicy().hasHeightForWidth())
        self.alarmTimeInput.setSizePolicy(sizePolicy)
        self.alarmTimeInput.setMinimumSize(QtCore.QSize(150, 50))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.alarmTimeInput.setFont(font)
        self.alarmTimeInput.setTime(QtCore.QTime(12, 0, 0))
        self.alarmTimeInput.setObjectName("alarmTimeInput")
        self.gridLayout_5.addWidget(self.alarmTimeInput, 3, 0, 1, 2, QtCore.Qt.AlignRight)
        self.toneLabel = QtWidgets.QLabel(self.SettingsPage)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(179, 163, 105))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(179, 163, 105))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.toneLabel.setPalette(palette)
        self.toneLabel.setObjectName("toneLabel")
        self.gridLayout_5.addWidget(self.toneLabel, 4, 7, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignBottom)
        self.setAlarmButton = QtWidgets.QPushButton(self.SettingsPage)
        self.setAlarmButton.setMinimumSize(QtCore.QSize(150, 40))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.setAlarmButton.setPalette(palette)
        self.setAlarmButton.setObjectName("setAlarmButton")
        self.gridLayout_5.addWidget(self.setAlarmButton, 6, 1, 1, 1, QtCore.Qt.AlignHCenter)
        spacerItem3 = QtWidgets.QSpacerItem(20, 50, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.gridLayout_5.addItem(spacerItem3, 7, 7, 1, 1)
        self.volumeLabel = QtWidgets.QLabel(self.SettingsPage)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(179, 163, 105))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(179, 163, 105))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.volumeLabel.setPalette(palette)
        self.volumeLabel.setObjectName("volumeLabel")
        self.gridLayout_5.addWidget(self.volumeLabel, 1, 7, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignBottom)
        self.brewButton = QtWidgets.QPushButton(self.SettingsPage)
        self.brewButton.setMinimumSize(QtCore.QSize(135, 40))
        self.brewButton.setObjectName("brewButton")
        self.gridLayout_5.addWidget(self.brewButton, 6, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.delayTimeInput = QtWidgets.QTimeEdit(self.SettingsPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.delayTimeInput.sizePolicy().hasHeightForWidth())
        self.delayTimeInput.setSizePolicy(sizePolicy)
        self.delayTimeInput.setMinimumSize(QtCore.QSize(150, 50))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.delayTimeInput.setFont(font)
        self.delayTimeInput.setObjectName("delayTimeInput")
        self.gridLayout_5.addWidget(self.delayTimeInput, 3, 2, 1, 2, QtCore.Qt.AlignHCenter)
        self.pages.addWidget(self.SettingsPage)
        self.AlarmPage = QtWidgets.QWidget()
        self.AlarmPage.setObjectName("AlarmPage")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.AlarmPage)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.snoozeButton = QtWidgets.QPushButton(self.AlarmPage)
        self.snoozeButton.setMinimumSize(QtCore.QSize(175, 50))
        self.snoozeButton.setObjectName("snoozeButton")
        self.gridLayout_4.addWidget(self.snoozeButton, 5, 2, 1, 1, QtCore.Qt.AlignLeft)
        self.wakeUpLabel = QtWidgets.QLabel(self.AlarmPage)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(179, 163, 105))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(179, 163, 105))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.wakeUpLabel.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(36)
        self.wakeUpLabel.setFont(font)
        self.wakeUpLabel.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.wakeUpLabel.setScaledContents(False)
        self.wakeUpLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.wakeUpLabel.setObjectName("wakeUpLabel")
        self.gridLayout_4.addWidget(self.wakeUpLabel, 2, 0, 1, 3, QtCore.Qt.AlignHCenter)
        self.outButton = QtWidgets.QPushButton(self.AlarmPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.outButton.sizePolicy().hasHeightForWidth())
        self.outButton.setSizePolicy(sizePolicy)
        self.outButton.setMinimumSize(QtCore.QSize(175, 50))
        self.outButton.setObjectName("outButton")
        self.gridLayout_4.addWidget(self.outButton, 5, 0, 1, 1, QtCore.Qt.AlignRight)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem4, 0, 1, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem5, 6, 1, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem6, 5, 1, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.gridLayout_4.addItem(spacerItem7, 3, 1, 1, 1)
        self.pages.addWidget(self.AlarmPage)
        self.SnoozePage = QtWidgets.QWidget()
        self.SnoozePage.setObjectName("SnoozePage")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.SnoozePage)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.snoozeOffButton = QtWidgets.QPushButton(self.SnoozePage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.snoozeOffButton.sizePolicy().hasHeightForWidth())
        self.snoozeOffButton.setSizePolicy(sizePolicy)
        self.snoozeOffButton.setMinimumSize(QtCore.QSize(225, 50))
        self.snoozeOffButton.setMaximumSize(QtCore.QSize(190, 40))
        self.snoozeOffButton.setObjectName("snoozeOffButton")
        self.gridLayout_3.addWidget(self.snoozeOffButton, 3, 0, 1, 1, QtCore.Qt.AlignHCenter)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem8, 9, 0, 1, 1)
        self.snoozeLabel = QtWidgets.QLabel(self.SnoozePage)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(179, 163, 105))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(179, 163, 105))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.snoozeLabel.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(36)
        self.snoozeLabel.setFont(font)
        self.snoozeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.snoozeLabel.setObjectName("snoozeLabel")
        self.gridLayout_3.addWidget(self.snoozeLabel, 1, 0, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.gridLayout_3.addItem(spacerItem9, 0, 0, 1, 1)
        self.pages.addWidget(self.SnoozePage)
        self.gridLayout_2.addWidget(self.pages, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.pages.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.nextAlarmLabel.setText(_translate("MainWindow", "Next alarm: 7:00 AM"))
        self.timeLabel.setText(_translate("MainWindow", "7:00 AM"))
        self.settingsButton.setText(_translate("MainWindow", "Settings"))
        self.statusLabel.setText(_translate("MainWindow", "Alarm: OFF\n"
"Brew:  OFF\n"
"Alarm: OFF"))
        self.settingsTitleLabel.setText(_translate("MainWindow", "Alarm Settings"))
        self.alarmTimeLabel.setText(_translate("MainWindow", "Alarm time"))
        self.label.setText(_translate("MainWindow", "Brew time"))
        self.homeButton.setText(_translate("MainWindow", "Home"))
        self.lightsButton.setText(_translate("MainWindow", "Lights: OFF"))
        self.toneLabel.setText(_translate("MainWindow", "Alarm tone: Buzzer"))
        self.setAlarmButton.setText(_translate("MainWindow", "Alarm: OFF"))
        self.volumeLabel.setText(_translate("MainWindow", "Volume: 25"))
        self.brewButton.setText(_translate("MainWindow", "Brew: OFF"))
        self.snoozeButton.setText(_translate("MainWindow", "Snooze"))
        self.wakeUpLabel.setText(_translate("MainWindow", "Rise and Shine\n"
"The current time is 7:00 AM"))
        self.outButton.setText(_translate("MainWindow", "Dimiss"))
        self.snoozeOffButton.setText(_translate("MainWindow", "Snooze off"))
        self.snoozeLabel.setText(_translate("MainWindow", "Snoozing until 7:05 AM"))

